import { GeneratedDocument, Template, TemplateVariable } from '../types';

export const seedTemplates: Template[] = [
  {
    id: 'template-1',
    name: 'Договор поставки оборудования',
    category: 'Договоры',
    tags: ['поставка', 'оборудование'],
    format: 'docx',
    status: 'published',
    version: 3,
    createdAt: '2026-06-20',
    variableCount: 9,
  },
  {
    id: 'template-2',
    name: 'Акт выполненных работ',
    category: 'Акты',
    tags: ['услуги'],
    format: 'pdf',
    status: 'draft',
    version: 1,
    createdAt: '2026-06-22',
    variableCount: 6,
  },
  {
    id: 'template-3',
    name: 'Дополнительное соглашение',
    category: 'Соглашения',
    tags: ['договор', 'изменения'],
    format: 'docx',
    status: 'published',
    version: 2,
    createdAt: '2026-06-24',
    variableCount: 7,
  },
];

export const seedVariables: TemplateVariable[] = [
  {
    id: 'var-1',
    templateId: 'template-1',
    name: 'contract_number',
    label: 'Номер договора',
    type: 'text',
    required: true,
    defaultValue: '',
    hint: 'Например: ТМ-26/104',
  },
  {
    id: 'var-2',
    templateId: 'template-1',
    name: 'contract_date',
    label: 'Дата договора',
    type: 'date',
    required: true,
    defaultValue: '2026-06-26',
    hint: '',
  },
  {
    id: 'var-3',
    templateId: 'template-1',
    name: 'customer_name',
    label: 'Заказчик',
    type: 'text',
    required: true,
    defaultValue: '',
    hint: 'Полное наименование организации',
  },
  {
    id: 'var-4',
    templateId: 'template-1',
    name: 'supplier_name',
    label: 'Поставщик',
    type: 'text',
    required: true,
    defaultValue: 'ООО "TrueMachine"',
    hint: '',
  },
  {
    id: 'var-5',
    templateId: 'template-1',
    name: 'total_amount',
    label: 'Сумма договора',
    type: 'currency',
    required: true,
    defaultValue: '',
    hint: 'Сумма в рублях',
  },
  {
    id: 'var-6',
    templateId: 'template-1',
    name: 'payment_terms',
    label: 'Условия оплаты',
    type: 'select',
    required: true,
    defaultValue: 'Предоплата 50%',
    hint: '',
    options: ['Предоплата 50%', 'Постоплата 100%', 'Оплата по этапам'],
  },
  {
    id: 'var-7',
    templateId: 'template-1',
    name: 'include_warranty',
    label: 'Включить гарантийный раздел',
    type: 'boolean',
    required: false,
    defaultValue: 'true',
    hint: '',
  },
  {
    id: 'var-8',
    templateId: 'template-1',
    name: 'comment',
    label: 'Комментарий',
    type: 'textarea',
    required: false,
    defaultValue: '',
    hint: 'Дополнительные условия для документа',
  },
  {
    id: 'var-15',
    templateId: 'template-1',
    name: 'items',
    label: 'Позиции',
    type: 'table',
    required: false,
    defaultValue: '',
    hint: 'Добавьте товары или услуги',
    options: {
      columns: ['Наименование', 'Кол-во', 'Цена'],
    },
  },
  {
    id: 'var-9',
    templateId: 'template-2',
    name: 'act_number',
    label: 'Номер акта',
    type: 'text',
    required: true,
    defaultValue: '',
    hint: '',
  },
  {
    id: 'var-10',
    templateId: 'template-2',
    name: 'work_description',
    label: 'Описание работ',
    type: 'textarea',
    required: true,
    defaultValue: '',
    hint: '',
  },
  {
    id: 'var-11',
    templateId: 'template-2',
    name: 'amount',
    label: 'Стоимость работ',
    type: 'currency',
    required: true,
    defaultValue: '',
    hint: '',
  },
  {
    id: 'var-12',
    templateId: 'template-3',
    name: 'agreement_number',
    label: 'Номер соглашения',
    type: 'text',
    required: true,
    defaultValue: '',
    hint: '',
  },
  {
    id: 'var-13',
    templateId: 'template-3',
    name: 'base_contract_number',
    label: 'Номер основного договора',
    type: 'text',
    required: true,
    defaultValue: '',
    hint: '',
  },
  {
    id: 'var-14',
    templateId: 'template-3',
    name: 'new_deadline',
    label: 'Новый срок',
    type: 'date',
    required: true,
    defaultValue: '',
    hint: '',
  },
];

export const seedDocuments: GeneratedDocument[] = [
  {
    id: 'doc-1',
    templateId: 'template-1',
    templateName: 'Договор поставки оборудования',
    author: 'frontend.user',
    createdAt: '2026-06-25T10:30:00',
    format: 'docx',
    fileName: 'Договор_ТМ-26-101_25-06-2026.docx',
    values: {
      contract_number: 'ТМ-26/101',
      contract_date: '2026-06-25',
      customer_name: 'АО "Север"',
      total_amount: '450000',
      include_warranty: true,
      items: [
        {
          Наименование: 'Станок',
          'Кол-во': '1',
          Цена: '450000',
        },
      ],
    },
  },
];
